@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
          Вооружённые Силы Российской Федерации
        </h1> 
      </section>
      <!-- Main content -->
      <section class="content">
          <div class="row">
              <!--Левые гербы-->
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3" style="padding-left: 8%;">
                  <img src="{{ asset('img/emblems/gerb-s-flot.png') }}" alt="" class="iconButton" data-tab="tab_6" data-img="{{ asset('img/maps/map5.png') }}" data-url="/districts/5">
                  <img src="{{ asset('img/emblems/west.png') }}" alt="" class="iconButton" data-tab="tab_2" data-img="{{ asset('img/maps/map1.png') }}" data-url="/districts/1">
                  <img src="{{ asset('img/emblems/south.png') }}" alt="" class="iconButton" data-tab="tab_1" data-img="{{ asset('img/maps/map2.png') }}" data-url="/districts/5">
              </div>
              <!-- Карта -->
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" id="mapCol">
                  <!-- Image Map Generated by http://www.image-map.net/ -->
                  <img id="russiaMapImg" src={{ asset('img/maps/map0.png') }} style="padding: 0;" width="100%" usemap="#image-map">
                  <map name="image-map">
                      <area target="" data-img="{{ asset('img/maps/map2.png') }}" data-icon="img/emblems/south.png" data-tab="tab_1" alt="ЮВО" title="ЮВО" coords="103,366,108,364,112,365,116,365,115,369,120,372,124,374,126,376,127,380,125,384,130,385,132,389,136,392,136,396,132,397,128,402,125,405,120,406,118,411,121,416,118,421,123,423,124,432,126,437,121,438,123,444,119,446,110,445,107,443,101,448,93,448,92,452,94,455,93,460,89,467,87,471,87,482,87,488,83,488,76,488,74,480,70,471,68,468,72,465,68,460,59,455,57,452,57,448,54,443,50,437,46,434,44,429,40,424,36,422,36,408,34,406,34,400,31,397,30,393,26,387,22,384,17,383,13,378,8,381,2,375,6,371,5,365,3,358,9,357,9,360,16,362,21,363,25,368,28,372,28,378,34,383,38,386,47,387,50,383,55,384,58,378,67,378,72,380,77,375,83,371,87,369,92,371,97,371,101,369" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map1.png') }}" data-icon="img/emblems/west.png" data-tab="tab_2" data-url="/districts/1" alt="ЗВО" title="ЗВО" coords="185,176,190,181,191,188,196,188,196,193,196,200,192,203,190,206,188,211,186,215,187,220,185,225,181,225,178,229,176,232,176,237,178,238,176,241,175,245,171,248,168,254,168,261,172,266,178,271,184,273,188,277,192,280,195,280,200,284,203,285,207,290,204,293,200,293,200,297,199,303,197,306,197,311,191,311,186,313,185,317,188,319,190,321,188,323,184,323,180,325,175,325,171,325,168,330,169,334,166,335,165,341,162,343,158,340,153,342,149,339,149,333,144,332,140,332,136,334,132,337,129,338,127,343,128,348,129,353,126,354,121,357,116,360,116,363,112,363,110,361,106,362,101,363,99,366,97,368,92,368,88,367,85,365,84,361,82,358,79,355,78,347,74,342,69,336,71,332,71,327,70,323,71,318,75,317,74,309,70,306,66,303,63,301,68,295,70,292,73,294,79,295,80,289,80,280,84,274,90,268,88,263,85,260,85,256,83,252,86,247,89,242,92,240,93,235,97,234,101,230,107,226,111,224,116,222,124,227,123,217,124,215,155,214,159,212,161,202,165,199,168,195,170,191,172,187,176,184,180,184,182,180" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map1.png') }}" data-icon="img/emblems/west.png" data-tab="tab_2" data-url="/districts/1" alt="ЗВО" title="ЗВО" coords="34,218,36,223,41,230,46,232,49,229,46,224,46,220,42,220,38,215" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map3.png') }}" data-icon="img/emblems/center.png" data-tab="tab_3" alt="ЦВО" title="ЦВО" coords="117,368,125,373,128,375,128,382,132,384,134,388,137,391,139,394,141,398,143,404,147,400,154,398,159,398,166,396,171,399,177,402,181,406,184,410,186,414,186,418,186,422,190,421,192,425,202,425,208,428,213,429,216,435,222,441,225,439,229,442,236,443,240,438,236,433,232,426,239,425,239,419,249,420,248,415,247,409,254,410,263,410,271,411,277,413,281,412,290,412,298,413,304,411,310,413,317,415,318,420,316,425,317,428,323,428,324,433,333,433,330,440,336,441,346,438,353,435,352,439,357,444,362,451,363,460,366,465,368,471,369,477,373,481,376,480,378,477,382,482,388,485,393,482,398,483,402,487,406,494,410,497,414,501,420,501,424,499,424,502,429,506,434,504,441,503,445,498,450,496,457,492,462,489,467,486,471,489,479,488,484,495,495,496,507,496,512,491,510,482,508,477,514,468,511,463,513,457,520,451,525,455,532,458,536,460,542,461,546,465,549,469,554,470,556,468,559,463,564,458,565,453,569,449,573,444,576,440,577,430,578,425,573,420,573,411,574,406,570,403,574,397,577,394,584,393,586,388,594,389,600,390,604,389,608,385,611,379,614,376,616,379,616,382,621,381,623,378,624,375,617,371,617,362,619,359,623,360,627,360,626,358,622,353,619,350,617,347,613,350,610,349,608,346,604,343,596,343,594,348,593,355,590,357,590,362,587,365,586,367,584,362,580,365,573,367,572,370,566,370,564,368,564,345,560,343,559,340,559,336,559,333,554,332,553,324,550,320,547,320,545,321,544,317,546,315,544,311,539,313,534,313,529,312,529,303,531,298,528,293,525,290,526,285,521,283,525,276,525,271,523,264,522,258,517,251,522,247,525,243,529,244,528,237,531,235,531,230,537,224,533,219,532,215,529,212,525,208,524,202,521,200,522,196,521,193,518,195,518,200,514,204,509,205,506,208,506,205,509,201,512,198,514,194,515,190,517,186,520,182,522,178,523,174,524,170,521,168,523,166,520,162,518,159,513,158,508,158,503,158,501,161,498,161,500,158,496,157,491,157,494,153,493,150,488,149,484,153,482,156,480,160,481,165,477,167,475,170,472,172,467,174,464,174,459,174,456,176,452,178,447,180,443,183,438,186,437,190,436,194,435,196,434,201,436,203,433,204,429,205,413,205,412,209,413,214,413,219,417,223,418,228,414,229,411,225,407,222,405,220,400,222,394,222,393,226,399,233,395,233,389,231,389,224,391,220,392,212,387,221,381,224,381,230,381,236,379,241,377,247,376,255,382,256,386,257,389,258,391,261,392,264,392,269,390,272,392,276,394,277,390,278,388,275,388,271,390,269,388,264,386,261,381,261,377,264,377,268,376,273,372,277,370,281,366,283,360,285,355,285,348,282,347,278,353,280,358,280,362,277,367,273,371,270,372,264,373,260,371,256,372,247,374,239,376,234,377,228,377,223,381,218,382,212,381,208,375,206,371,205,366,210,363,214,358,220,353,224,353,231,351,236,349,241,351,243,352,247,352,251,354,254,351,257,350,259,348,256,346,251,342,247,338,244,337,248,339,253,335,256,338,261,337,264,328,271,319,273,314,276,313,278,308,279,304,281,301,285,297,285,296,283,292,286,290,289,290,294,286,298,283,301,283,305,282,309,280,312,278,315,276,317,273,318,269,318,264,316,261,313,246,314,245,311,239,311,239,309,233,308,232,313,228,314,225,315,223,314,217,312,213,312,212,316,209,310,208,305,212,300,214,296,211,290,205,295,201,295,203,298,201,301,199,306,198,311,194,312,187,315,192,320,188,324,183,324,179,327,175,327,173,328,171,331,172,334,168,336,166,340,164,344,161,345,159,344,155,343,153,345,149,341,148,336,145,334,139,334,133,340,130,340,130,348,130,354,127,356,118,361,117,365" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map4.png') }}" data-icon="img/emblems/east.png" data-tab="tab_4" alt="ВВО" title="ВВО" coords="520,452,515,457,513,462,514,466,518,468,524,469,529,471,535,471,541,476,543,481,550,483,560,482,563,479,572,478,585,479,591,484,605,483,613,482,619,477,627,471,628,466,632,462,638,461,642,462,649,459,660,459,667,452,669,447,667,442,667,433,669,426,670,420,666,416,662,416,663,410,668,405,673,402,676,398,682,398,688,397,698,397,704,400,712,407,716,412,723,415,728,423,735,422,742,420,750,421,757,421,761,427,767,429,772,426,776,422,776,419,778,415,780,412,781,409,787,407,788,410,791,413,790,419,794,424,794,428,795,434,797,439,797,444,795,448,791,448,788,452,787,456,785,458,787,461,791,465,795,471,797,477,795,484,799,485,801,479,801,471,805,470,809,471,815,470,819,465,822,459,823,439,823,426,823,423,823,411,820,398,818,384,819,378,805,356,798,347,798,340,800,339,809,342,817,352,824,360,827,366,833,370,838,376,842,382,850,390,852,389,847,382,848,379,856,379,856,375,849,376,845,372,838,371,834,366,833,361,830,357,830,351,835,350,835,347,824,341,814,333,808,332,802,325,802,322,794,317,791,311,785,313,788,317,791,321,788,323,790,326,794,331,797,335,798,337,796,338,794,337,791,336,790,334,785,334,787,329,779,328,770,327,766,331,769,337,765,339,763,342,760,339,758,339,758,342,755,342,753,338,749,338,746,340,742,341,740,338,741,332,743,326,745,319,744,311,743,296,745,292,743,285,745,279,743,270,747,266,754,257,760,254,760,250,766,247,768,243,770,241,769,237,772,233,776,229,782,227,783,232,786,233,788,226,791,223,790,219,792,218,794,214,795,211,791,213,788,211,785,206,785,201,784,196,782,191,780,186,780,181,782,177,783,173,786,172,787,166,790,172,794,175,798,175,800,172,799,167,798,161,797,157,795,154,790,149,790,145,794,140,796,141,794,144,796,148,799,151,803,153,805,155,806,157,807,160,807,163,806,168,808,171,810,175,812,181,813,187,816,191,818,196,819,200,819,204,818,210,818,215,822,221,824,227,830,233,835,239,844,242,851,244,856,249,863,252,870,255,874,257,879,260,884,259,883,252,881,246,874,238,871,234,872,229,874,225,869,224,865,220,864,215,864,211,868,207,868,203,861,202,856,200,853,195,853,191,855,188,851,186,847,186,843,183,840,179,837,179,836,183,831,183,827,181,826,176,826,171,822,169,819,165,819,161,821,157,822,154,820,150,820,148,824,148,823,145,823,142,823,137,825,134,826,131,828,128,832,128,834,128,834,125,832,121,831,118,830,113,827,108,826,103,824,98,823,92,823,87,820,82,819,77,822,75,826,70,822,66,817,65,812,68,809,67,804,66,798,70,795,73,792,70,798,66,799,63,799,60,797,55,792,51,786,50,783,46,786,44,794,44,795,39,796,34,805,34,808,29,813,26,812,20,806,16,798,16,802,12,798,10,799,7,795,3,791,7,786,9,784,13,781,17,781,20,790,20,785,26,780,24,777,23,770,26,766,29,761,32,757,35,752,40,745,44,742,46,738,52,733,57,730,63,726,68,723,73,724,76,731,78,736,81,735,85,727,87,724,84,722,81,720,85,721,90,721,93,716,99,712,103,710,109,708,114,703,117,698,114,696,112,691,113,687,115,682,119,679,124,678,130,673,135,668,134,664,137,661,136,657,138,657,133,651,133,648,138,646,142,646,146,643,144,639,146,641,141,638,141,633,143,628,148,624,149,625,154,623,160,627,157,631,164,632,168,626,171,622,174,618,176,618,181,610,181,607,180,607,186,610,192,610,195,604,194,598,191,594,189,589,186,593,183,591,181,586,174,578,173,574,175,567,175,566,181,568,186,562,189,553,192,548,187,539,190,533,194,530,191,526,193,522,193,524,199,525,203,528,207,531,211,534,214,535,219,538,221,539,225,537,228,533,231,532,235,531,239,531,244,528,246,523,248,521,251,522,256,525,259,525,264,527,268,527,273,529,278,524,281,527,285,529,291,533,297,533,303,532,307,532,310,537,311,545,310,548,314,547,318,552,319,555,325,556,330,561,331,561,336,561,341,566,344,567,349,566,354,566,360,566,366,570,369,573,367,573,365,579,364,581,360,584,361,586,363,589,361,588,357,592,354,592,347,596,341,605,342,611,345,613,348,616,344,621,348,626,354,628,359,626,362,622,362,620,361,620,366,620,371,625,373,626,378,623,382,619,383,615,384,614,382,615,379,611,382,609,385,608,388,605,390,601,391,597,392,595,391,586,391,586,394,578,395,577,398,572,400,577,405,575,409,575,415,577,419,577,423,580,424,580,427,579,432,578,436,578,440,575,444,572,447,570,450,567,454,565,458,561,463,558,466,558,471,553,471,550,470,546,468,544,465,538,462,534,462,529,458,524,456" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map4.png') }}" data-icon="img/emblems/east.png" data-tab="tab_4" alt="ВВО" title="ВВО" coords="751,331,756,330,754,327" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map4.png') }}" data-icon="img/emblems/east.png" data-tab="tab_4" alt="ВВО" title="ВВО" coords="888,384,892,380,891,376,887,380" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map4.png') }}" data-icon="img/emblems/east.png" data-tab="tab_4" alt="ВВО" title="ВВО" coords="894,363,891,360" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map4.png') }}" data-icon="img/emblems/east.png" data-tab="tab_4" alt="ВВО" title="ВВО" coords="886,277,882,267" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map4.png') }}" data-icon="img/emblems/east.png" data-tab="tab_4" alt="ВВО" title="ВВО" coords="881,178,875,176" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map4.png') }}" data-icon="img/emblems/east.png" data-tab="tab_4" alt="ВВО" title="ВВО" coords="832,169,828,163" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map4.png') }}" data-icon="img/emblems/east.png" data-tab="tab_4" alt="ВВО" title="ВВО" coords="728,40,719,24" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map5.png') }}" data-icon="img/emblems/center.png" data-tab="tab_6" alt="СФ" title="СФ" coords="209,289,213,289,216,294,214,301,210,307,212,312,217,310,222,311,226,313,231,311,231,306,240,305,242,311,246,311,249,312,255,312,262,312,266,314,271,316,275,316,278,313,281,308,282,302,283,298,286,296,287,293,289,292,290,288,291,286,295,281,299,281,300,283,303,280,307,278,312,277,315,273,320,271,327,270,327,267,333,266,335,264,333,262,336,260,333,258,333,256,336,253,336,248,334,246,338,241,329,233,326,233,324,231,322,233,322,237,319,241,315,241,314,243,311,242,313,238,312,236,306,237,300,233,294,233,286,232,291,227,291,225,285,225,277,225,262,225,258,227,254,230,249,227,247,222,248,218,254,217,258,218,258,210,252,201,251,208,247,210,245,214,242,217,242,222,238,227,233,228,233,224,230,220,225,221,220,220,212,221,210,227,209,230,205,230,200,223,199,218,198,215,195,216,195,220,196,225,195,228,192,229,187,225,183,226,180,228,178,231,178,234,180,238,179,242,177,243,176,248,172,250,170,253,169,258,171,262,175,266,181,269,185,271,188,273,191,277,194,276,198,281,201,281,203,280,206,285" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map5.png') }}" data-icon="img/emblems/center.png" data-tab="tab_6" alt="СФ" title="СФ" coords="271,213,275,209,278,213,277,217,273,216" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map5.png') }}" data-icon="img/emblems/center.png" data-tab="tab_6" alt="СФ" title="СФ" coords="217,156,211,154,205,155,200,157,199,165,196,168,191,169,185,173,191,179,192,186,197,186,201,181,200,187,204,194,207,201,210,205,210,210,215,213,227,214,231,210,234,203,232,194,232,179,222,163,226,157" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map5.png') }}" data-icon="img/emblems/center.png" data-tab="tab_6" alt="СФ" title="СФ" coords="321,228,322,223,320,220,318,221,318,225" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map5.png') }}" data-icon="img/emblems/center.png" data-tab="tab_6" alt="СФ" title="СФ" coords="316,212,315,205,316,196,320,190,328,183,335,178,341,173,348,171,353,167,361,165,373,164,381,161,385,156,384,153,377,153,371,156,365,156,359,154,354,156,347,156,340,161,336,165,330,169,324,171,322,176,319,178,314,179,311,185,304,187,300,191,305,195,306,201,304,205,308,210" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map5.png') }}" data-icon="img/emblems/center.png" data-tab="tab_6" alt="СФ" title="СФ" coords="351,84,354,93,370,103,392,103,396,97,375,90,357,80" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map5.png') }}" data-icon="img/emblems/center.png" data-tab="tab_6" alt="СФ" title="СФ" coords="450,126,468,139,474,147,484,144,490,138,481,128,471,121,465,113,465,106,459,103,451,116" shape="poly">
                      <area target="" data-img="{{ asset('img/maps/map5.png') }}" data-icon="img/emblems/center.png" data-tab="tab_6" alt="СФ" title="СФ" coords="587,125,604,115,618,108,630,104,629,118,618,123,611,134,600,139,589,134" shape="poly">
                  </map>
              </div>
              <!--Правые гербы-->
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3" style="padding-left: 8%; padding-top: 5%">
                  <img src="{{ asset('img/emblems/center.png') }}" alt="" class="iconButton" data-tab="tab_3" data-img="{{ asset('img/maps/map3.png') }}" data-url="/districts/5">
                  <img src="{{ asset('img/emblems/east.png') }}" alt="" class="iconButton" data-tab="tab_4" data-img="{{ asset('img/maps/map4.png') }}" data-url="/districts/5">
              </div>
              <!-- Предзагрузка картинок -->
              <img src="{{ asset('img/maps/map1.png') }}" alt="" class="hidden">
              <img src="{{ asset('img/maps/map2.png') }}" alt="" class="hidden">
              <img src="{{ asset('img/maps/map3.png') }}" alt="" class="hidden">
              <img src="{{ asset('img/maps/map4.png') }}" alt="" class="hidden">
              <img src="{{ asset('img/maps/map5.png') }}" alt="" class="hidden">
					</div>
				@if (Auth::check())
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<!-- Custom Tabs -->
							<div class="nav-tabs-custom">
								<ul class="nav nav-tabs pull-right">
									<li class="pull-left active"><a href="#tab_5" data-toggle="tab"  data-img="{{ asset('img/maps/map0.png') }}" data-icon=img/gerb.png>Вооружённые Силы Российской Федерации</a></li>
									<li class=""><a href="#tab_4" data-toggle="tab" data-img="{{ asset('img/maps/map4.png') }}" data-icon="img/emblems/east.png">ВВО</a></li>
									<li class=""><a href="#tab_3" data-toggle="tab" data-img="{{ asset('img/maps/map3.png') }}" data-icon="img/emblems/center.png">ЦВО</a></li>
									<li class=""><a href="#tab_1" data-toggle="tab"  data-img="{{ asset('img/maps/map2.png') }}" data-icon="img/emblems/south.png">ЮВО</a></li>
									<li class=""><a href="#tab_2" data-toggle="tab" data-img="{{ asset('img/maps/map1.png') }}" data-icon="img/emblems/west.png">ЗВО</a></li>
									<li class=""><a href="#tab_6" data-toggle="tab"  data-img="{{ asset('img/maps/map5.png') }}" data-icon="img/emblems/gerb-s-flot.png">СФ</a></li>
								</ul>
								@php
									$tabPanes = [
										[
												'id' => 'tab_1',
												'title' => 'Южный военный округ',
										],
										[
												'id' => 'tab_2',
												'title' => 'Западный военный округ',
										],
										[
												'id' => 'tab_3',
												'title' => 'Центральный военный округ',
										],
										[
												'id' => 'tab_4',
												'title' => 'Восточный военный округ',
										],
										[
												'id' => 'tab_6',
												'title' => 'Северный флот',
										]
									];
								@endphp

							<div class="tab-content">
								<div class="tab-pane active" id="tab_5">
									<div class="row">
									<div class="col-xs-4">
										<div class="info-box bg-aqua-gradient">
										<span class="info-box-icon"><i class="fa fa-tint"></i></span>

										<div class="info-box-content">
											<span class="info-box-text">Холодная вода</span>
											<span class="info-box-number"><span class="random"></span> м<sup>3</sup></span>

											<div class="progress">
											<div class="progress-bar" style="width: 12%"></div>
											</div>
												<span class="progress-description">
												расход с 01.05.2018
												</span>
										</div>
										<!-- /.info-box-content -->
										</div>
										<div class="row">
										<div class="col-xs-12">
											<div class="chart-responsive">
											<canvas id="pieChartWater" height="310" width="976" style="width: 488px; height: 155px;"></canvas>
											</div>
											<!-- ./chart-responsive -->
										</div>
										<!-- /.col -->
										<div class="col-xs-12">
											<ul class="chart-legend clearfix text-center">
											<li><i class="fa fa-circle-o text-red"></i> Южный военный округ</li>
											<li><i class="fa fa-circle-o text-green"></i> Западный военный округ</li>
											<li><i class="fa fa-circle-o text-yellow"></i> Центральный военный округ</li>
											<li><i class="fa fa-circle-o text-aqua"></i> Восточный военный округ</li>
											<li><i class="fa fa-circle-o text-blue"></i> Северный флот</li>
											</ul>
										</div>
										<!-- /.col -->
										</div>                                    
									</div>
									<div class="col-xs-4">
										<div class="info-box bg-yellow-gradient">
										<span class="info-box-icon"><i class="fa fa-flash"></i></span>

										<div class="info-box-content">
											<span class="info-box-text">Электроэнергия</span>
											<span class="info-box-number"><span class="random"></span> кВт-ч</span>

											<div class="progress">
											<div class="progress-bar" style="width: 12%"></div>
											</div>
												<span class="progress-description">
												расход с 01.05.2018
												</span>
										</div>
										<!-- /.info-box-content -->
										</div>                
										<div class="row">
										<div class="col-xs-12">
											<div class="chart-responsive">
											<canvas id="pieChartElectro" height="310" width="976" style="width: 488px; height: 155px;"></canvas>
											</div>
											<!-- ./chart-responsive -->
										</div>
										<!-- /.col -->
										<div class="col-xs-12">
											<ul class="chart-legend clearfix text-center">
											<li><i class="fa fa-circle-o text-red"></i> Южный военный округ</li>
											<li><i class="fa fa-circle-o text-green"></i> Западный военный округ</li>
											<li><i class="fa fa-circle-o text-yellow"></i> Центральный военный округ</li>
											<li><i class="fa fa-circle-o text-aqua"></i> Восточный военный округ</li>
											<li><i class="fa fa-circle-o text-blue"></i> Северный флот</li>
											</ul>
										</div>
										<!-- /.col -->
										</div>                                    
									</div>
									<div class="col-xs-4">
										<div class="info-box bg-red-gradient">
										<span class="info-box-icon"><i class="fa fa-fire"></i></span>

										<div class="info-box-content">
											<span class="info-box-text">Тепловая энергия</span>
											<span class="info-box-number"><span class="random"></span> ГКал</span>

											<div class="progress">
											<div class="progress-bar" style="width: 12%"></div>
											</div>
												<span class="progress-description">
												расход с 01.05.2018
												</span>
										</div>
										<!-- /.info-box-content -->
										</div>                
										<div class="row">
										<div class="col-xs-12">
											<div class="chart-responsive">
											<canvas id="pieChartHeat" height="310" width="976" style="width: 488px; height: 155px;"></canvas>
											</div>
											<!-- ./chart-responsive -->
										</div>
										<!-- /.col -->
										<div class="col-xs-12">
											<ul class="chart-legend clearfix text-center">
											<li><i class="fa fa-circle-o text-red"></i> Южный военный округ</li>
											<li><i class="fa fa-circle-o text-green"></i> Западный военный округ</li>
											<li><i class="fa fa-circle-o text-yellow"></i> Центральный военный округ</li>
											<li><i class="fa fa-circle-o text-aqua"></i> Восточный военный округ</li>
											<li><i class="fa fa-circle-o text-blue"></i> Северный флот</li>
											</ul>
										</div>
										<!-- /.col -->
										</div>                                    
									</div>
									<!-- /колонка ресурса -->
									</div>
								</div>

								@foreach ($tabPanes as $tabPane)
									<div class="tab-pane" id="{{ $tabPane['id'] }}">
										<h3>{{ $tabPane['title'] }}</h3>
										<div class="row">
											<div class="col-xs-4">
												<div class="info-box bg-aqua-gradient">
												<span class="info-box-icon"><i class="fa fa-tint"></i></span>
								
												<div class="info-box-content">
													<span class="info-box-text">Холодная вода</span>
													<span class="info-box-number"><span class="random"></span> м<sup>3</sup></span>
								
													<div class="progress">
													<div class="progress-bar" style="width: 12%"></div>
													</div>
														<span class="progress-description">
														расход с 01.05.2018
														</span>
												</div>
												<!-- /.info-box-content -->
												</div>                
											</div>
											<div class="col-xs-4">
												<div class="info-box bg-yellow-gradient">
												<span class="info-box-icon"><i class="fa fa-flash"></i></span>
								
												<div class="info-box-content">
													<span class="info-box-text">Электроэнергия</span>
													<span class="info-box-number"><span class="random"></span> кВт-ч</span>
								
													<div class="progress">
													<div class="progress-bar" style="width: 12%"></div>
													</div>
														<span class="progress-description">
														расход с 01.05.2018
														</span>
												</div>
												<!-- /.info-box-content -->
												</div>                
											</div>
											<div class="col-xs-4">
												<div class="info-box bg-red-gradient">
												<span class="info-box-icon"><i class="fa fa-fire"></i></span>
								
												<div class="info-box-content">
													<span class="info-box-text">Тепловая энергия</span>
													<span class="info-box-number"><span class="random"></span> ГКал</span>
								
													<div class="progress">
													<div class="progress-bar" style="width: 12%"></div>
													</div>
														<span class="progress-description">
														расход с 01.05.2018
														</span>
												</div>
												<!-- /.info-box-content -->
												</div>                
											</div>
										<!-- /колонка ресурса -->
										</div>
									</div>
								@endforeach
							</div>
							<!-- nav-tabs-custom -->
						</div>
					</div>
				@endif
      </section>
      <!-- /.content -->
@endsection

@section('scripts')
  <script src="{{ asset('js/pages/home.js') }}"></script>
@endsection
